# Generated by Django 4.2.6 on 2023-10-22 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Question'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Reply'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='userbase',
            options={'verbose_name_plural': 'UserBase'},
        ),
        migrations.AddField(
            model_name='reply',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.question'),
        ),
    ]
