# Generated by Django 4.2.6 on 2023-10-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_question_options_alter_reply_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='mainapp.tags'),
        ),
    ]
