# Generated by Django 4.2.6 on 2023-10-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_mtmquestionrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtmquestionrating',
            name='is_positive',
            field=models.BooleanField(default=False),
        ),
    ]
