# Generated by Django 4.2.6 on 2023-10-26 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_mtmquestionrating_is_positive'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTMReplyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField(default=False)),
                ('reply_rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.reply')),
                ('user_rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
